# Cleaning the Datasets
### Import necessary packages

In [1]:
import pandas as pd
import re
import os

### Create `normalize_title` function to standardize titles across datasets

In [2]:
def normalize_title(title):
    """
    Consistent title formatting used across ALL datasets for joining
    ex. "Spider-Man: No Way Home" becomes "spiderman no way home"
    """
    title = str(title).lower()
    title = re.sub(r"[^\w\s]", "", title)  # removes all punctuation
    title = re.sub(r"\s+", " ", title)      # removes extra whitespace
    return title.strip()

### IMDb Basics Dataset
Filtered for movies from 2010-2024

In [3]:
# Load only relevant columns, treat \N as missing
imdb_basics = pd.read_csv("../data/raw/title.basics.tsv", sep = "\t",
    usecols = ["tconst", "titleType", "primaryTitle", "startYear", "runtimeMinutes", "genres"],
    dtype = str,
    na_values = "\\N")

# Drop all rows with any missing values
imdb_basics = imdb_basics.dropna()

# Keep only movies
imdb_basics = imdb_basics[imdb_basics["titleType"] == "movie"]

# Convert startYear to numeric, drop the invalid conversions
imdb_basics["startYear"] = pd.to_numeric(imdb_basics["startYear"])

# Filter for movies between 2010–2024
imdb_basics = imdb_basics[imdb_basics["startYear"].between(2010, 2024)]

# Normalize movie titles
imdb_basics["norm_title"] = imdb_basics["primaryTitle"].apply(normalize_title)

# Keep only relevant columns
imdb_basics = imdb_basics[["norm_title", "tconst", "titleType", "startYear", "runtimeMinutes", "genres"]]

print(f"Movies in IMDb basics (2010–2024): {len(imdb_basics)}")

Movies in IMDb basics (2010–2024): 202133

In [4]:
imdb_basics.head()

,norm_title,tconst,titleType,startYear,runtimeMinutes,genres
61097,the tango of the widower and its distorting mi...,tt0062336,movie,2020,70,Drama
67649,the other side of the wind,tt0069049,movie,2018,122,Drama
69136,socialist realism,tt0070596,movie,2023,78,"Drama,History"
76036,histórias de combóios em portugal,tt0077684,movie,2022,46,Documentary
98012,the wandering soap opera,tt0100275,movie,2017,80,"Comedy,Drama,Fantasy"

### IMDb Ratings Dataset
Filter for movies that have at least 30 000 votes, removing movies with unreliable number of ratings.

In [5]:
#Load IMDb Ratings dataset
imdb_ratings = pd.read_csv("../data/raw/title.ratings.tsv", sep = "\t",
    na_values = "\\N")

print(f"Ratings loaded: {len(imdb_ratings)}")

Ratings loaded: 1652901

In [6]:
imdb_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2200
1  tt0000002            5.5       312
2  tt0000003            6.4      2311
3  tt0000004            5.1       196
4  tt0000005            6.2      3038

Added `averageRating` column to the `imdb_basics` dataset by matching the unique title constants, `tconst`

In [7]:
# Merge IMDb basics with ratings
movies = pd.merge(imdb_basics, imdb_ratings, on = "tconst", how = "left")

# Drop rows with missing ratings
movies = movies.dropna(subset = ["averageRating"])

# Keep only movies with 30 000+ votes (removes obscure movies with unreliable ratings)
movies = movies[movies["numVotes"] >= 30000]

print(f"Movies with 300 or more votes: {len(movies)}")

Movies with 300 or more votes: 2812

### Box Office Dataset

In [8]:
# Load box office dataset
boxoffice = pd.read_csv("../data/raw/enhanced_box_office_data(2000-2024)u.csv")

boxoffice = boxoffice.dropna(subset = ["$Worldwide"]) # Drops rows missing values for worldwide revenue
boxoffice = boxoffice.drop_duplicates() # Removes duplicate rows

boxoffice = boxoffice[(boxoffice["Year"] >= 2010) & (boxoffice["Year"] <= 2024)] # Filters for Movies between 2010 and 2024

boxoffice["norm_title"] = boxoffice["Release Group"].apply(normalize_title)

boxoffice = boxoffice[["norm_title", "Genres", "Year", "$Worldwide"]]

print(f"Box Office loaded: {len(boxoffice)}")

Box Office loaded: 3000

In [9]:
boxoffice.head()

,norm_title,Genres,Year,$Worldwide
2000,toy story 3,"Animation, Family, Comedy",2010,1.066970e+09
2001,alice in wonderland,"Family, Fantasy, Adventure",2010,1.025467e+09
2002,harry potter and the deathly hallows part 1,"Adventure, Fantasy",2010,9.602833e+08
2003,inception,"Action, Science Fiction, Adventure",2010,8.282587e+08
2004,shrek forever after,"Comedy, Adventure, Fantasy, Animation, Family",2010,7.526009e+08

### Rotten Tomatoes Dataset
Filtered for critic reviews with at least 170 characters, removing low-effort consensus entries with insufficient detail.

In [10]:
# Load Rotten Tomatoes dataset; drop rows missing consensus or ratings
rotten = pd.read_csv("../data/raw/rotten_tomatoes_movies.csv",
    usecols = ["movie_title", "critics_consensus", "tomatometer_rating"])

rotten = rotten.dropna(subset = ["critics_consensus", "tomatometer_rating"])
rotten["norm_title"] = rotten["movie_title"].apply(normalize_title)

rotten = rotten[["norm_title", "critics_consensus", "tomatometer_rating"]] # Drop movie_title, use norm_title

# Keep only reviews with a substantial critics consensus, at least 170 characters
rotten = rotten[rotten["critics_consensus"].str.len() >= 170]

print(f"Rotton Tomatoes loaded: {len(rotten)}")

Rotton Tomatoes loaded: 2091

In [11]:
rotten.head()

,norm_title,critics_consensus,tomatometer_rating
1,please give,Nicole Holofcener's newest might seem slight i...,87.0
37,the matador,"This humorously amoral, oddball comic thriller...",75.0
43,the alamo,John Wayne proves to be less compelling behind...,52.0
44,g,Race and class struggles come to the Hamptons ...,24.0
50,aliens,"While Alien was a marvel of slow-building, atm...",97.0

The column names of all dataframe are printed to select the one that are relevant to our database design and research questions. These chosen columns will become the attributes in our SQL tables.

Due to the large imported datasets, filtering was applied to each dataset to accommodate database quota limitations. The IMDb dataset was filtered to movies released between 2010–2024 with at least 300 votes, the Rotten Tomatoes dataset was filtered to reviews with a critics consensus of at least 170 characters.

### Save all cleaned datasets to CSV file

In [12]:
movies.to_csv("../data/clean/movies_clean.csv", index=False)
boxoffice.to_csv("../data/clean/boxoffice_clean.csv", index=False)
rotten.to_csv("../data/clean/rotten_clean.csv", index=False)